---
title: "ETRm Threshold Over Time"
author: "Abby"
date: "2024-08-19"
output:
  html_document: default
  pdf_document: default
---

```{r}
#Let's bring in our data
datos <- read.csv("OFAV_PAM_P1_11Jun2024.csv")

#Looks good, but we need to get rid of the sacrifices
class(datos$Treatment) #Character
unique(datos$Treatment) #We need to get rid of "x" 

#Making a new dataframe without the sacrifice treatments
datos.no.sac <- datos[ which(datos$Treatment != "x"), ]

#Now we need to make our days more quantitative
dias <- read.csv("RecoveryPhaseDays.csv")

datos.days <- merge(datos.no.sac, dias, by = "Recovery.Phase")
```

```{r}
#So let's make a ggplot with error bars like we've done frequently before.

#But first we need some stats
library(Rmisc)

#How we calculate
ETRm.stats = summarySE(datos.days, measurevar="ETRm", 
                            groupvars = c("Days.Post.Experiment", "Treatment"))

#And now we plot what we calculated
library(ggplot2)
library(ggpubr)
p1 <- ggplot(ETRm.stats, aes(x=Days.Post.Experiment, y= ETRm, colour=Treatment)) + 
  geom_pointrange(aes(ymin = ETRm - se, ymax = ETRm + se))+
  scale_color_manual(values = c("black", "#1E90FF", "#000080", "#881B1B"),
                     name = "Turbidity NTU")+
  geom_line(size = 1)+
  geom_point()+
  ylim(0, 125)+
  scale_x_continuous(breaks=c(-4, 0, 28, 49, 70, 91))+
  xlab("Time in Days Post Experiment")+
  ylab("ETRm")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  ggtitle("ETRm of Turbidity Treatments Over Time")

p1

```