---
title: "InitialYNPQ"
author: "Abby"
date: "2024-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Bringing in our data and cleaning it up

```{r}
#Let's bring in our data
datos <- read.csv("OFAV_PAM_FDEP(Recovery P2)11Jun2024.csv")

#Looks good, but we need to get rid of the sacrifices
class(datos$Treatment) #Character
unique(datos$Treatment)

#Making a new dataframe without the sacrifice treatments
datos.no.sac <- datos[ which(datos$Treatment != "x"), ]

#Making a new dataframe without the sacrifice treatments
datos.no.sac <- datos[ which(datos$Treatment != "x"), ]

#Now we have to do some subsituting for consistency with other plots
class(datos.no.sac$Treatment) #Character
unique(datos.no.sac$Treatment) #"NT" "T"  "0"  "N"

#We also need to re-name our treatments for consistency with other graphs
datos.no.sac$Treatment <- sub("0", "Control", datos.no.sac$Treatment)
datos.no.sac$Treatment <- sub("NT", "high temp high ntu", datos.no.sac$Treatment)
datos.no.sac$Treatment <- sub("N", "high ntu", datos.no.sac$Treatment)
datos.no.sac$Treatment <- sub("T", "high temp", datos.no.sac$Treatment)


#And we have to do this in multiple steps to prevent replacement in the middle of words
datos.no.sac$Treatment <- sub("high", "High", datos.no.sac$Treatment)
#Apparently this only replaces the first "high" in each string, but we can fix that later
#Remember, it's only stupid if it doesn't work
datos.no.sac$Treatment <- sub("temp", "Temp", datos.no.sac$Treatment)
datos.no.sac$Treatment <- sub("high ntu", "High NTU", datos.no.sac$Treatment)
datos.no.sac$Treatment <- sub("ntu", "NTU", datos.no.sac$Treatment)

#So now we want before the experimental treatments interfered with anything
principio <- datos.no.sac[ which(datos.no.sac$Recovery.Phase == "a"), ]
```
Bringing in some stuff we apparently need to graph
```{r}
#So now I think we can graph it
#And now let's make our graph
#And I guess we need to bring these in if we want the thing to work
source("R_rainclouds.R") #With the sources we need to copy them into the same project for unfortunate reasons
source("summarySE.R") #With the sources we need to copy them into the same project for unfortunate reasons
library(cowplot)
library(readr)
library(ggplot2)
library(dplyr)
```
```{r}
p1 <- ggplot(principio, aes(x=as.character(Genotype), y = Y.NPQ., color = as.character(Genotype)))+
  geom_flat_violin(position = position_nudge(x = .25, y = 0),adjust =2, trim = FALSE, )+
  geom_point(position = position_jitter(width = .15), size = .25)+
  #geom_hline(yintercept = 0, color = "black", linetype = "dashed")+
  #Keeps the points from invisible-izing the boxplot
  geom_boxplot(aes(x =as.character(Genotype) , y = Y.NPQ.),outlier.shape = NA, alpha = 0.3, width = .1) +
  #scale_y_continuous(limits = c(-0.1, 0.15))+
  #theme_cowplot()+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  xlab("Genotype")+
  ylab("YNPQ")+
  ggtitle("YNPQ by Genotype Phase 2")

p1
```



So it looks like we do have some variability. I guess let's see if it meet ANOVA assumptions
```{r}
#Now we try for ANOVA or Kruskall-Wallis
res_aov <- aov(Y.NPQ. ~ as.factor(Genotype),
  data = principio
)

#Making some plots to visualize
par(mfrow = c(1, 2)) # combine plots

# histogram
hist(res_aov$residuals)

# QQ-plot
library(car)

qqPlot(res_aov$residuals,
  id = FALSE # id = FALSE to remove point identification
)
#Potentially meets assumptions
```

```{r}
#We'll test it too
shapiro.test(res_aov$residuals) #p-value = 0.06674 normal

```

```{r}
#How about homogenous?
leveneTest(Y.NPQ.~ as.factor(Genotype), data = principio)
#Not homogenous. Got to do a Kruskall-Wallis
```

```{r}
#So let's try a Kruskal test instead
kruskal.test(Y.NPQ.~ as.factor(Genotype), data = principio)
#Significant
```

```{r}
library(FSA)
dunnTest(Y.NPQ. ~ as.factor(Genotype),
         data=principio,
         method="bonferroni")

#50 is significantly different from 80
#50 is significantly different from 90
#90 is not signficantly different from 80
#67 is signficantly different from 90
#67 is not significantly different from 80
#84 is significantly different from 90
#84 is not significantly different from 80 or 67
#80 is significantly different from 97
#84 is not significantly different from 97
#90 is significantly different from 97
```